release: device services
edgexfoundry/cd-management pull request #116
Opened 2021-01-28 23:54 UTC by bill-mahoney

We're now ready to go with the dot releases of the device services. 
These all just come from the HEAD of the master branches, versions are as follows:

device-modbus-go  v1.3.1
device-mqtt-go   v1.3.1
device-random  v1.3.1
device-virtual-go v1.3.1
device-snmp-go v1.3.1
device-grove-c v1.3.1
device-bacnet-c v1.3.1
device-rest-go v1.2.1
device-camera-go  v1.2.1

Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>

2021-01-29 00:58 UTC, iain-anderson approved these changes
LGTM

2021-01-29 03:02 UTC, soda480 approved these changes
LGTM

2021-01-29 12:32 UTC, iain-anderson requested changes
Looks like we have an issue with device-grove-c
Please wait

2021-02-01 17:24 UTC, ernestojeda approved these changes
LGTM

2021-02-02 20:23 UTC, merged