release(jakarta): tag go-mod group 1
edgexfoundry/cd-management pull request #209
Opened 2021-11-09 03:26 UTC by bill-mahoney

Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>

2021-11-09 15:06 UTC, ernestojeda approved these changes
LGTM

2021-11-09 16:12 UTC, lenny-intel requested changes

2021-11-09 16:59 UTC, lenny-intel approved these changes
LGTM

2021-11-10 17:17 UTC, lenny-intel approved these changes
LGTM

2021-11-10 17:18 UTC, merged