To be merged Nov 17th - release(jakarta): release device-services
edgexfoundry/cd-management pull request #217
Opened 2021-11-15 22:34 UTC by bill-mahoney

Needs to be updated to the latest commitID before merged.

Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>

2021-11-16 16:07 UTC, lenny-intel requested changes

2021-11-16 16:07 UTC, lenny-intel commented on release/device-modbus-go.yaml
> +commitId: '558c40fbdebbe4b00a0283e0ecd9585407ec2bc6'
```suggestion
commitId: '3366fcb7b8cfa87a3d941489b4b63a155443012c'
```
This is the final commit for the release.

2021-11-16 16:07 UTC, lenny-intel commented on release/device-mqtt-go.yaml
> +commitId: 'f142b7d4d9dc0d163bb8d716c4eb7ddee57de476'
Waiting on last issue to be implemented and merged. 
https://github.com/edgexfoundry/device-mqtt-go/issues/321

2021-11-16 16:07 UTC, lenny-intel commented on release/device-rest-go.yaml
> +commitId: '09739088bb3ccddf347dd8b212f45a4687ee065f'
```suggestion
commitId: '7759c41568adf15208c0dd5cadcdb8f87895acd8'
```
This is the final commit for the release.

2021-11-16 16:07 UTC, lenny-intel commented on release/device-snmp-go.yaml
> +commitId: '8cef9076ddadae0bb4a2071504c212bd6ac7a64c'
```suggestion
commitId: 'd6a2d4438fc175be031f77f972aa414c83442272'
```
This is the final commit for the release.

2021-11-16 16:07 UTC, lenny-intel commented on release/device-virtual-go.yaml
> +commitId: 'ce5f781da4ac4c2a0d7531ae22c293687cd2d279'
```suggestion
commitId: 'd6a2d4438fc175be031f77f972aa414c83442272'
```

This is the final commit for the release.

2021-11-17 15:39 UTC, lenny-intel requested changes
We should also include Device Camera, but with LTS=false

2021-11-17 15:39 UTC, lenny-intel commented on release/device-modbus-go.yaml
> +commitId: '3366fcb7b8cfa87a3d941489b4b63a155443012c'
```suggestion
commitId: '494e11ba379638b0cea34cac06412dc20970075c'
```

2021-11-17 15:42 UTC, lenny-intel approved these changes
LGTM

2021-11-17 17:22 UTC, iain-anderson approved these changes
LGTM

2021-11-18 00:13 UTC, merged