To be merged Nov 17th - release(Jakarta): release Jakarta app services
edgexfoundry/cd-management pull request #218
Opened 2021-11-15 22:39 UTC by bill-mahoney

Needs to be updated to latest commitID before merged
Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>

2021-11-16 16:02 UTC, lenny-intel requested changes

2021-11-16 16:02 UTC, lenny-intel commented on release/app-service-configurable.yaml
> +commitId: '4ec47cdd8cea7a0176fb01ed614db2877bbe7fef'
```suggestion
commitId: 'bfff9069ec602defc1c67fa58b1ab94b3f5a4b73'
```
That is the final commit for release.

2021-11-17 15:48 UTC, lenny-intel approved these changes
LGTM

2021-11-17 16:26 UTC, lenny-intel approved these changes
LGTM

2021-11-17 23:09 UTC, ernestojeda approved these changes
ready, set, go!

2021-11-17 23:11 UTC, merged