feat: Add Docker Hub description for device-uart
edgexfoundry/cd-management pull request #366
Opened 2023-08-19 07:28 UTC by vediyappan-villali

Add service to descriptions/image_descriptions.txt and add MD files to image-overview-templates/new-names

Close #22 in device-uart

## PR Checklist
Please check if your PR fulfills the following requirements:

- [N] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [N] I am not introducing a new dependency (add notes below if you are)
- [N] I have added unit tests for the new feature or bug fix (if not, why?)
- [N] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [N] I have opened a PR for the related docs change (if not, why?)
  N/A

## Testing Instructions
N/A

## New Dependency Instructions (If applicable)
N/A

2023-08-19 07:36 UTC, vediyappan-villali commented
@lenny-intel @cloudxxx8 Please check. Addresses. https://github.com/edgexfoundry/device-uart/issues/22.

2023-08-21 16:47 UTC, lenny-intel requested changes

2023-08-21 16:47 UTC, lenny-intel commented on image-overview-templates/new-names/device-uart-arm64.md
> +        - [Dockerfile](https://github.com/edgexfoundry/device-uart/blob/v2.2.0/Dockerfile)
Remove as these do not exists.

2023-08-21 16:47 UTC, lenny-intel commented on image-overview-templates/new-names/device-uart.md
> +        - [Dockerfile](https://github.com/edgexfoundry/device-uart/blob/v2.2.0/Dockerfile)
Remove as these do not exists.

2023-08-22 04:47 UTC, vediyappan-villali commented on image-overview-templates/new-names/device-uart.md
> +        - [Dockerfile](https://github.com/edgexfoundry/device-uart/blob/v2.2.0/Dockerfile)
Removed.

2023-08-22 04:47 UTC, vediyappan-villali commented on image-overview-templates/new-names/device-uart-arm64.md
> +        - [Dockerfile](https://github.com/edgexfoundry/device-uart/blob/v2.2.0/Dockerfile)
Removed.

2023-08-22 16:06 UTC, lenny-intel approved these changes
LGTM

2023-08-22 16:07 UTC, merged